### ISSUE TITLE
email should be base64 encoded, or MessageVerifier barfs on some characters

### ISSUE THREAD

**Issue by mepster** [ankane/mailkick#5]
For example with the email 'foo+123@bar.com', the '+' character causes a problem.

You can fix with this in processor.rb:
      # email must be base64 encoded, e.g., for '+' character, or MessageVerifier barfs
      encoded_email = Base64.encode64(email)
      token = verifier.generate([encoded_email, user.try(:id), user.try(:class).try(:name), list])

and this in subscriptions_controller.rb:
        # email must be base64 encoded, e.g., for '+' character, or MessageVerifier barfs
        encoded_email, user_id, user_type, @list = verifier.verify(params[:id])
        @email = Base64.decode64(encoded_email)

**Comment by ankane** [comment]
@mepster what version of Mailkick are you on?  this should be fixed in 0.1.1

**Comment by mepster** [comment]
I'm on 0.1.1.

In my local copy of processor.rb, I do have that change to from 0.1.1 that looks like an attempt to fix (a related problem?)... 
-        part.body.raw_source.gsub!(/%7B%7BMAILKICK_TOKEN%7D%7D/, token)
+        part.body.raw_source.gsub!(/%7B%7BMAILKICK_TOKEN%7D%7D/, CGI::escape(token))

... but that doesn't fix the error I am getting.

The error I get is "Subscription not found" in subscriptions_controller.rb because the call to verifier.verify raises InvalidSignature, here:
gems/activesupport-4.2.0/lib/active_support/message_verifier.rb, line 49

I only get the error if I try an email with a '+' in it... otherwise it works fine. The code changes I suggested above fix it for me.

**Comment by ankane** [comment]
Hey @mepster, I was never able to reproduce after 0.1.1 fix, so going to close.
